[project]
name = "server"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "cryptography>=46.0.1",
    "fastapi[all]>=0.116.2",
    "markitdown[docx,outlook,pdf,pptx,xls,xlsx]>=0.1.3",
    "pytz>=2025.2",
]
